# Generated by Django 2.0 on 2018-02-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('phone_num', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('game_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.Game')),
                ('current_date', models.DateField(auto_now=True)),
                ('customer_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
            ],
        ),
    ]
